### ISSUE TITLE
project fails to compile with latest vala 0.38

### ISSUE THREAD

**Issue by decathorpe** [elementary/wingpanel-indicator-datetime#45]
This is hitting the same problem as https://github.com/elementary/calendar/issues/143, where property names seem to get overloaded by accident now, and the names "first" and "last" have to be avoided.

```
(...)/build/src/Widgets/calendar/Util.c:59:2: error: redeclaration of enumerator 'UTIL_DATE_RANGE_LAST_PROPERTY'
  UTIL_DATE_RANGE_LAST_PROPERTY
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(...)/build/src/Widgets/calendar/Util.c:56:2: note: previous definition of 'UTIL_DATE_RANGE_LAST_PROPERTY' was here
  UTIL_DATE_RANGE_LAST_PROPERTY,
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/datetime.dir/build.make:274: src/CMakeFiles/datetime.dir/Widgets/calendar/Util.c.o] Error 1
```

**Comment by tintou** [comment]
Fixed by #48
